# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.IntegerField(max_length=128, unique=True)),
                ('url', models.CharField(max_length=1000, unique=True, validators=[django.core.validators.URLValidator])),
                ('name', models.CharField(max_length=128)),
                ('twitter_name', models.CharField(max_length=128, unique=True)),
                ('text', models.CharField(max_length=256)),
            ],
        ),
    ]
