# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.IntegerField(unique=True),
        ),
    ]
