# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='confidence_score',
        ),
    ]
