# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170801_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='confidence_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tweet',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='retweet_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
