# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170803_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
