# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tweet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='favorite_count',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='retweet_count',
        ),
    ]
