# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tweet_formatted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='', max_length=256),
        ),
    ]
