# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170804_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
