# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170805_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='formatted_text',
            field=models.CharField(default='', max_length=252),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='', max_length=251),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
