# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170805_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='formatted_text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
