# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170805_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
