# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170805_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
